export interface IActionType {
    type: string;
    payload?: any;
}

const actionTypes = {
    // auth
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_ERROR: 'SIGN_IN_ERROR',
    TIMESTAMP_CREATE_SUCCESS: 'TIMESTAMP_CREATE_SUCCESS',
    TIMESTAMP_CREATE_ERROR: 'TIMESTAMP_CREATE_ERROR',
    TIMESTAMP_SELECT: 'TIMESTAMP_SELECT',
    TIMESTAMP_DELETE_SUCCESS: 'TIMESTAMP_DELETE_SUCCESS',
    TIMESTAMP_DELETE_ERROR: 'TIMESTAMP_DELETE_ERROR',
    PROJECT_CREATE_SUCCESS: 'PROJECT_CREATE_SUCCESS',
    PROJECT_CREATE_ERROR: 'PROJECT_CREATE_ERROR',
    PROJECT_SELECT: 'PROJECT_SELECT'
}

export default actionTypes;